spin_manifest_version = 2

[application]
name = "cncfwatchparty"
version = "0.1.0"
authors = ["Michelle Dhanani <michelle@fermyon.com>"]
description = "watch cncf spin sandbox application vote"

[variables]
github_pat = { required = true }

[[trigger.http]]
route = "/..."
component = "cncfwatchparty"

[component.cncfwatchparty]
source = "target/wasm32-wasip1/release/cncfwatchparty.wasm"
allowed_outbound_hosts = ["https://api.github.com"]
[component.cncfwatchparty.build]
command = "cargo build --target wasm32-wasip1 --release"
watch = ["src/**/*.rs", "Cargo.toml"]
[component.cncfwatchparty.variables]
github_pat = "{{github_pat}}"
